python -m IncompleteBaseline.dev.main --tensorboard-log-dir "IncompleteBaseline/dev/logs/qdn/maze5x5/dynamic_epsilon/mabrollout/v1" \
    --width 5 \
    --height 5 \
    --max-episode-steps-eval 25 \
    --max-episode-steps 2500 \
    --max-episode-steps-warmup 5000 \
    --total-time-steps 1228800 \
    --learning-starts 819200 \
    --epsilon-strategy "StepDecay" \
    --epsilon-decay 204800 \
    --epsilon-exploration-strategy "MABRollout" \
    --random-rollout-stategy "MABRollout" \
    --seed 42
python -m IncompleteBaseline.dev.main --tensorboard-log-dir "IncompleteBaseline/dev/logs/qdn/maze5x5/dynamic_epsilon/uniform/v1" \
    --width 5 \
    --height 5 \
    --max-episode-steps-eval 25 \
    --max-episode-steps 2500 \
    --max-episode-steps-warmup 5000 \
    --total-time-steps 1228800 \
    --learning-starts 819200 \
    --epsilon-strategy "StepDecay" \
    --epsilon-decay 204800 \
    --seed 42