"""Train a Stable-Baselines3 DQN agent on the procedural maze environment.

The maze environment generates every single-solution maze, splits them into a
training and an evaluation set, and samples a random maze on every reset. This
script mirrors the reference DQN-for-maze setup in
IncompleteBaseline/dev/main.py plus dev/maze4x4/run_dqn_91.sh (DQN with
net_arch=[64, 32], constant 0.1 exploration, per-step Polyak target updates and
Adam at 5e-5) while using SB3's built-in DQN implementation.

Metrics reported next to return and episode length:

* eval/success_rate: fraction of held-out mazes solved (goal reached).
* training/return, training/steps, training/success_rate: the same metrics on
  the training split, matching the reference implementation.
* final_eval/return, final_eval/steps, final_eval/success_rate: a final greedy
  pass over the held-out set.

Two details require care when combining SB3 with this environment:

* Maze selects the held-out evaluation set only when it is reset with
  options={"is_evaluation": True}, but EvalCallback and evaluate_policy reset
  without options. EvaluationMaze injects that option so evaluation never
  samples training mazes.
* A maze episode succeeds when the agent reaches the goal, which the
  environment reports as terminated. MazeInfo surfaces that as
  info["is_success"] so SB3's EvalCallback can log eval/success_rate.

Maze generation is expensive, so the evaluation environments share the dataset
generated by the training environment instead of regenerating it.

The SB3 policy uses a custom feature extractor with the reference QNetwork's
Linear + LayerNorm + ReLU hidden layers. The reference DQN also used an
auxiliary actor head, which plain SB3 DQN lacks.

Run from the repository root with the rl conda environment:

    /Users/jay/miniconda3/envs/rl/bin/python -m IncompleteBaseline.dev.debug.main_sb3_dqn

or choose another maze size:

    /Users/jay/miniconda3/envs/rl/bin/python -m IncompleteBaseline.dev.debug.main_sb3_dqn \
        --width 5 --height 5 \
        --tensorboard-log-dir IncompleteBaseline/dev/debug/logs/env/sb3_dqn/maze5x5/v1
"""

from __future__ import annotations

import argparse
import logging
import random
import sys
from pathlib import Path

import gymnasium as gym
import numpy as np
import torch
from torch import nn
from stable_baselines3 import DQN
from stable_baselines3.common.callbacks import BaseCallback, CallbackList, EvalCallback
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
from stable_baselines3.common.monitor import Monitor

# Allow both package execution and direct execution of this debug entry point.
if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
    from IncompleteBaseline.envs.procedual_maze.env import Maze
else:
    from ...envs.procedual_maze.env import Maze


# Defaults mirror IncompleteBaseline/dev/main.py and dev/maze4x4/run_dqn_91.sh.
WIDTH = 4
HEIGHT = 4
TOTAL_TIMESTEPS = 204800
LEARNING_STARTS = 102_400
BUFFER_SIZE = 500_000
BATCH_SIZE = 64
GAMMA = 0.99
TAU = 0.005                    # soft target update, applied every env step
TRAIN_FREQ = 1
GRADIENT_STEPS = 1
EPSILON = 0.1                  # fixed 90% greedy / 10% random exploration
LEARNING_RATE = 1e-3           # Historical maze-DQN setting that reaches ~70%.
NET_ARCH = [128, 128, 64, 32]  # Historical high-performing maze architecture.
MAX_EPISODE_STEPS = 1600       # Longer training episodes expose more goal-reaching transitions.
MAX_EPISODE_STEPS_EVAL = 16    # Evaluation horizon used by the historical maze runs.
EVAL_EPISODES = 100
EVAL_FREQ = 10_000
SEED = 42
LOG_DIR = "IncompleteBaseline/dev/debug/logs/env/sb3_dqn/maze4x4/v2"


class EvaluationMaze(gym.Wrapper):
    """Reset the maze in evaluation mode so the held-out split is sampled.

    Maze.reset picks the training or the evaluation maze pool from the
    is_evaluation reset option. SB3's EvalCallback and evaluate_policy reset
    without options, which would silently evaluate on the training mazes; this
    wrapper forces the option to True.
    """

    def reset(self, *, seed: int | None = None, options: dict | None = None):
        env_options = dict(options or {})
        env_options["is_evaluation"] = True
        return self.env.reset(seed=seed, options=env_options)


class MazeInfo(gym.Wrapper):
    """Surface the maze success signal as info["is_success"].

    A maze episode is a success when the agent reaches the goal, which the
    environment reports as terminated. SB3's EvalCallback reads
    info["is_success"] at the end of every evaluated episode to compute and log
    success_rate, so the signal is added here.
    """

    def step(self, action):
        observation, reward, terminated, truncated, info = self.env.step(action)
        info = dict(info)
        info["is_success"] = bool(terminated)
        return observation, reward, terminated, truncated, info


class MazeFeatureExtractor(BaseFeaturesExtractor):
    """Match the reference maze Q-network's LayerNorm MLP trunk for SB3."""

    def __init__(self, observation_space: gym.Space) -> None:
        super().__init__(observation_space, features_dim=NET_ARCH[-1])
        input_dim = int(np.prod(observation_space.shape))
        layers: list[nn.Module] = []
        previous_width = input_dim
        for width in NET_ARCH:
            layers.extend((nn.Linear(previous_width, width), nn.LayerNorm(width), nn.ReLU()))
            previous_width = width
        self.network = nn.Sequential(*layers)

    def forward(self, observations: torch.Tensor) -> torch.Tensor:
        return self.network(torch.flatten(observations, start_dim=1))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--width", type=int, default=WIDTH)
    parser.add_argument("--height", type=int, default=HEIGHT)
    parser.add_argument(
        "--total-timesteps", "--total-time-steps",
        type=int, default=TOTAL_TIMESTEPS,
        help="Total number of calls to env.step during training.",
    )
    parser.add_argument("--learning-starts", type=int, default=LEARNING_STARTS)
    parser.add_argument(
        "--learning-rate", type=float, default=LEARNING_RATE,
        help="Adam learning rate for SB3 DQN.",
    )
    parser.add_argument(
        "--epsilon", type=float, default=EPSILON,
        help="Fixed epsilon for epsilon-greedy exploration (no decay).",
    )
    parser.add_argument("--replay-capacity", type=int, default=BUFFER_SIZE)
    parser.add_argument("--batch-size", type=int, default=BATCH_SIZE)
    parser.add_argument("--gamma", type=float, default=GAMMA)
    parser.add_argument("--tau", type=float, default=TAU)
    parser.add_argument("--max-episode-steps", type=int, default=MAX_EPISODE_STEPS)
    parser.add_argument("--max-episode-steps-eval", type=int, default=MAX_EPISODE_STEPS_EVAL)
    parser.add_argument("--evaluation-episodes", type=int, default=EVAL_EPISODES)
    parser.add_argument("--evaluation-frequency", type=int, default=EVAL_FREQ)
    parser.add_argument("--tensorboard-log-dir", type=str, default=LOG_DIR)
    parser.add_argument("--seed", type=int, default=SEED)
    return parser.parse_args()


def create_maze_environments(
    *,
    seed: int,
    width: int,
    height: int,
    train_step_limitation: int,
    eval_step_limitation: int,
) -> tuple[Maze, gym.Env, Maze]:
    """Build the training and evaluation mazes sharing one generated dataset.

    Returns:
        training_env: sampled by SB3 while training.
        eval_env: forced onto the held-out split, ready for EvalCallback.
        train_eval_env: a separate instance that samples the training split, so
            the training metrics can be reported without stepping the training
            environment out from under SB3.
    """
    logger = logging.getLogger(__name__)

    logger.info("Generating the %sx%s maze dataset (this can take a while).", width, height)
    training_env = Maze(
        width=width,
        height=height,
        train_step_limitation=train_step_limitation,
        eval_step_limitation=eval_step_limitation,
    )
    training_env.generate_maze(seed=seed)
    logger.info("Training mazes: %d", training_env.training_mazes.shape[0])
    logger.info("Evaluation mazes: %d", training_env.evaluation_mazes.shape[0])

    def make_eval_maze() -> Maze:
        env = Maze(
            width=width,
            height=height,
            train_step_limitation=eval_step_limitation,
            eval_step_limitation=eval_step_limitation,
        )
        env.training_mazes = training_env.training_mazes
        env.evaluation_mazes = training_env.evaluation_mazes
        return env

    # Monitor on the outside silences SB3's "not wrapped with Monitor" warning
    # while EvaluationMaze still forces the held-out split on every reset.
    eval_env = Monitor(MazeInfo(EvaluationMaze(make_eval_maze())))
    train_eval_env = make_eval_maze()
    return training_env, eval_env, train_eval_env


def evaluate_maze(
    model: DQN,
    env: gym.Env,
    n_eval_episodes: int,
) -> tuple[float, float, float, float]:
    """Run greedy episodes and return return, return std, steps and success rate.

    Success is reaching the goal, which the environment reports as terminated
    rather than truncated by the step limit.
    """
    returns: list[float] = []
    lengths: list[int] = []
    successes = 0

    observation, _ = env.reset()
    for _ in range(n_eval_episodes):
        total_reward = 0.0
        steps = 0
        while True:
            action, _ = model.predict(observation, deterministic=True)
            observation, reward, terminated, truncated, _ = env.step(action)
            total_reward += float(reward)
            steps += 1
            if terminated or truncated:
                successes += int(terminated)
                break
        returns.append(total_reward)
        lengths.append(steps)
        observation, _ = env.reset()

    return (
        float(np.mean(returns)),
        float(np.std(returns)),
        float(np.mean(lengths)),
        successes / n_eval_episodes,
    )


class TrainingEvalCallback(BaseCallback):
    """Log return, steps and success rate on the training maze split.

    The reference implementation reports training-set metrics alongside the
    held-out ones; SB3's EvalCallback only covers the evaluation environment.
    """

    def __init__(
        self,
        train_eval_env: gym.Env,
        *,
        n_eval_episodes: int,
        eval_freq: int,
        verbose: int = 0,
    ) -> None:
        super().__init__(verbose)
        self.train_eval_env = train_eval_env
        self.n_eval_episodes = n_eval_episodes
        self.eval_freq = eval_freq

    def _on_step(self) -> bool:
        if self.eval_freq <= 0 or self.n_calls % self.eval_freq != 0:
            return True

        mean_return, _, mean_steps, success_rate = evaluate_maze(
            self.model, self.train_eval_env, self.n_eval_episodes
        )
        self.logger.record("training/return", mean_return)
        self.logger.record("training/steps", mean_steps)
        self.logger.record("training/success_rate", success_rate)
        self.logger.dump(self.num_timesteps)

        if self.verbose >= 1:
            print(
                f"Training split: return={mean_return:.2f} "
                f"steps={mean_steps:.1f} success={success_rate:.1%}"
            )
        return True


def build_model(env: gym.Env, args: argparse.Namespace) -> DQN:
    """Create the SB3 DQN with the reference maze hyperparameters."""
    if not 0.0 <= args.epsilon <= 1.0:
        raise ValueError("epsilon must be in [0, 1]")
    if args.learning_starts < args.batch_size:
        raise ValueError("learning_starts must be at least batch_size")

    return DQN(
        "MlpPolicy",
        env,
        learning_rate=args.learning_rate,
        buffer_size=args.replay_capacity,
        learning_starts=args.learning_starts,
        batch_size=args.batch_size,
        tau=args.tau,
        gamma=args.gamma,
        train_freq=TRAIN_FREQ,
        gradient_steps=GRADIENT_STEPS,
        max_grad_norm=10,               # reference implementation does no clipping
        target_update_interval=1,       # reference soft-updates after each step
        # Equal endpoints deliberately disable SB3's linear exploration decay.
        exploration_initial_eps=args.epsilon,
        exploration_final_eps=args.epsilon,
        # The extractor is the two-hidden-layer trunk; SB3 adds only its final
        # linear Q head, matching algorithms.common.qnetwork.QNetwork.
        policy_kwargs={"features_extractor_class": MazeFeatureExtractor, "net_arch": []},
        tensorboard_log=args.tensorboard_log_dir,
        seed=args.seed,
        device="cpu",
        verbose=1,
    )


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    args = parse_args()

    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    train_env, eval_env, train_eval_env = create_maze_environments(
        seed=args.seed,
        width=args.width,
        height=args.height,
        train_step_limitation=args.max_episode_steps,
        eval_step_limitation=args.max_episode_steps_eval,
    )

    try:
        model = build_model(train_env, args)

        eval_callback = EvalCallback(
            eval_env,
            n_eval_episodes=args.evaluation_episodes,
            eval_freq=args.evaluation_frequency,
            deterministic=True,
            best_model_save_path=str(Path(args.tensorboard_log_dir) / "best_model"),
            log_path=str(Path(args.tensorboard_log_dir) / "eval"),
            verbose=0,
        )
        training_callback = TrainingEvalCallback(
            train_eval_env,
            n_eval_episodes=args.evaluation_episodes,
            eval_freq=args.evaluation_frequency,
            verbose=1,
        )

        model.learn(
            total_timesteps=args.total_timesteps,
            callback=CallbackList([training_callback, eval_callback]),
        )

        mean_return, std_return, mean_steps, success_rate = evaluate_maze(
            model, eval_env, args.evaluation_episodes
        )
        model.logger.record("final_eval/return", mean_return)
        model.logger.record("final_eval/steps", mean_steps)
        model.logger.record("final_eval/success_rate", success_rate)
        model.logger.dump(model.num_timesteps)
        print(
            f"Final evaluation: return = {mean_return:.2f} +/- {std_return:.2f}, "
            f"steps = {mean_steps:.1f}, success rate = {success_rate:.1%}"
        )
    finally:
        train_env.close()
        eval_env.close()
        train_eval_env.close()


if __name__ == "__main__":
    main()
